--- #YAML:1.0
name:               MLDBM
version:            2.02
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Data::Dumper:  2.08
    perl:          5.004
resources:
    repository:  git://github.com/chorny/MLDBM.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
